### ISSUE TITLE
Could not build on ubuntu 18.04

### ISSUE THREAD

**Issue by SoGoDev** [Arman92/go-tdlib#44]
There is part of error log. Seems like there is no linking.

# github.com/Arman92/go-tdlib
/usr/local/lib/libtdcore.a(DialogFilter.cpp.o): In function `td::DialogFilter::get_dialog_filter(td::tl::unique_ptr<td::telegram_api::dialogFilter>, bool)':
DialogFilter.cpp:(.text._ZN2td12DialogFilter17get_dialog_filterENS_2tl10unique_ptrINS_12telegram_api12dialogFilterEEEb+0x125): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::reserve(unsigned long)'
DialogFilter.cpp:(.text._ZN2td12DialogFilter17get_dialog_filterENS_2tl10unique_ptrINS_12telegram_api12dialogFilterEEEb+0x17c): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::reserve(unsigned long)'
/usr/local/lib/libtdcore.a(DialogFilter.cpp.o): In function `td::DialogFilter::get_emoji_by_icon_name(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)':
DialogFilter.cpp:(.text._ZN2td12DialogFilter22get_emoji_by_icon_nameERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE+0x31): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/usr/local/lib/libtdcore.a(DialogFilter.cpp.o): In function `td::DialogFilter::init_icon_names()':
DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0x40f): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0x41b): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0x427): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0x433): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/usr/local/lib/libtdcore.a(DialogFilter.cpp.o):DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0x43f): more undefined references to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)' follow
/usr/local/lib/libtdcore.a(DialogFilter.cpp.o): In function `td::DialogFilter::init_icon_names()':
DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0xdb9): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::operator=(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0xdf5): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
DialogFilter.cpp:(.text._ZN2td12DialogFilter15init_icon_namesEv+0xe3d): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::reserve(unsigned long)'
/usr/local/lib/libtdcore.a(DialogFilter.cpp.o): In function `td::DialogFilter::get_icon_name() const':

**Comment by zzerding** [comment]
I build docker image go env and Arman92/to-tdlib for ubunt:18.04. 
You can try `docker run --rm -it -v "$PWD":/app  -w /app zzerding/go-build-tdlib go build`

**Comment by Psh777** [comment]
Some problem
